#include <jni.h>
#include <cctype>
#include <cmath>
#include <cstdlib>
#include <string>

namespace {
std::string utf(JNIEnv* e, jstring s){if(!s)return{};const char*p=e->GetStringUTFChars(s,nullptr);if(!p)return{};std::string r(p);e->ReleaseStringUTFChars(s,p);return r;}
jstring str(JNIEnv*e,const std::string&s){return e->NewStringUTF(s.c_str());}
std::string trim(const std::string&s){size_t a=0,b=s.size();while(a<b&&std::isspace((unsigned char)s[a]))a++;while(b>a&&std::isspace((unsigned char)s[b-1]))b--;return s.substr(a,b-a);}
std::string lower(std::string s){for(char&c:s)c=(char)std::tolower((unsigned char)c);return s;}
std::string quote(const std::string&s){std::string r="\"";for(unsigned char c:s){if(c=='\"')r+="\\\"";else if(c=='\\')r+="\\\\";else if(c=='\n')r+="\\n";else if(c=='\r')r+="\\r";else if(c=='\t')r+="\\t";else r+=(char)c;}return r+"\"";}
bool parse_port(const std::string&s,int*v){if(s.empty())return false;char*e=nullptr;long n=std::strtol(s.c_str(),&e,10);if(e==s.c_str()||*e||n<1||n>65535)return false;*v=(int)n;return true;}
bool parse_range(const std::string&s){int x;if(parse_port(trim(s),&x))return true;size_t p=s.find('-');if(p==std::string::npos||s.find('-',p+1)!=std::string::npos)return false;int a,b;return parse_port(trim(s.substr(0,p)),&a)&&parse_port(trim(s.substr(p+1)),&b)&&a<=b;}
bool parse_mbps(const std::string&s){char*e=nullptr;double n=std::strtod(s.c_str(),&e);return !s.empty()&&e!=s.c_str()&&*e=='\0'&&std::isfinite(n)&&n>0&&n<=100000;}
std::string decode(const std::string&s){std::string r;for(size_t i=0;i<s.size();i++){if(s[i]=='%'&&i+2<s.size()){char*e=nullptr;long n=std::strtol(s.substr(i+1,2).c_str(),&e,16);if(e&&*e=='\0'){r+=(char)n;i+=2;continue;}}r+=s[i]=='+'?' ':s[i];}return r;}
std::string query(const std::string&q,const std::string&key){size_t a=0;while(a<=q.size()){size_t b=q.find('&',a);std::string x=q.substr(a,b==std::string::npos?std::string::npos:b-a);size_t p=x.find('=');if(p!=std::string::npos&&decode(x.substr(0,p))==key)return decode(x.substr(p+1));if(b==std::string::npos)break;a=b+1;}return{};}
std::string field(const std::string&j,const std::string&key){std::string m="\""+key+"\"";size_t p=j.find(m);if(p==std::string::npos)return{};p=j.find(':',p+m.size());if(p==std::string::npos)return{};p++;while(p<j.size()&&std::isspace((unsigned char)j[p]))p++;if(p<j.size()&&j[p]=='\"'){std::string r;for(++p;p<j.size();p++){if(j[p]=='\\'&&p+1<j.size())r+=j[++p];else if(j[p]=='\"')break;else r+=j[p];}return r;}size_t z=j.find_first_of(",}",p);return trim(j.substr(p,z==std::string::npos?std::string::npos:z-p));}
std::string b64(const std::string&s){static const std::string A="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";std::string c;for(char x:s)if(!std::isspace((unsigned char)x)&&x!='=')c+=x=='-'?'+':x=='_'?'/':x;std::string r;unsigned int buf=0;int bits=0;for(char x:c){size_t v=A.find(x);if(v==std::string::npos)return{};buf=(buf<<6)|(unsigned)v;bits+=6;if(bits>=8){bits-=8;r+=(char)((buf>>bits)&255);}}return r;}
std::string stream_cfg(std::string n,std::string sec,std::string path,const std::string&host,const std::string&sni,const std::string&pbk,const std::string&sid,const std::string&fp,const std::string&alpn,const std::string&verify){n=lower(n);if(n=="websocket")n="ws";if(n=="mkcp")n="kcp";if(n=="raw")n="tcp";if(n=="xhttp2")n="xhttp";sec=lower(sec);if(sec!="tls"&&sec!="reality")sec="none";std::string p=path.empty()?"/":path,r="{\"network\":"+quote(n)+",\"security\":"+quote(sec);if(n=="ws")r+=",\"wsSettings\":{\"path\":"+quote(p)+",\"headers\":{\"Host\":"+quote(host)+"}}";else if(n=="grpc")r+=",\"grpcSettings\":{\"serviceName\":"+quote(trim(p))+",\"multiMode\":false}";else if(n=="xhttp"||n=="splithttp")r+=",\""+n+"Settings\":{\"path\":"+quote(p)+",\"host\":"+quote(host)+",\"mode\":\"stream-up\"}";else if(n=="h2"||n=="http")r+=",\"httpSettings\":{\"path\":"+quote(p)+",\"host\":["+quote(host)+"]}";else if(n=="httpupgrade")r+=",\"httpupgradeSettings\":{\"path\":"+quote(p)+",\"host\":"+quote(host)+"}";else if(n=="kcp")r+=",\"kcpSettings\":{\"header\":{\"type\":\"none\"},\"seed\":"+quote(host)+"}";else if(n=="tcp")r+=",\"tcpSettings\":{\"header\":{\"type\":\"none\"}}";else if(n=="quic")r+=",\"quicSettings\":{\"security\":\"none\",\"key\":\"\",\"header\":{\"type\":\"none\"}}";if(sec=="tls")r+=",\"tlsSettings\":{\"serverName\":"+quote(sni.empty()?host:sni)+",\"fingerprint\":"+quote(fp.empty()?"chrome":fp)+(verify.empty()?"":",\"verifyPeerCertByName\":"+quote(verify))+(alpn.empty()?"":",\"alpn\":["+quote(alpn)+"]")+"}";else if(sec=="reality")r+=",\"realitySettings\":{\"serverName\":"+quote(sni.empty()?host:sni)+",\"fingerprint\":"+quote(fp.empty()?"chrome":fp)+",\"publicKey\":"+quote(pbk)+",\"shortId\":"+quote(sid)+"}";return r+"}";}
std::string base_cfg(const std::string&proto,const std::string&host,int port,const std::string&id,const std::string&enc,const std::string&st,int socks){std::string user=proto=="vmess"?"{\"id\":"+quote(id)+",\"alterId\":0,\"security\":"+quote(enc)+"}":proto=="vless"?"{\"id\":"+quote(id)+",\"encryption\":\"none\"}":"{}";std::string settings=proto=="trojan"?"{\"servers\":[{\"address\":"+quote(host)+",\"port\":"+std::to_string(port)+",\"password\":"+quote(id)+"}]}":"{\"vnext\":[{\"address\":"+quote(host)+",\"port\":"+std::to_string(port)+",\"users\":["+user+"]}]}";return "{\"log\":{\"loglevel\":\"warning\"},\"inbounds\":[{\"listen\":\"127.0.0.1\",\"port\":" + std::to_string(socks) + ",\"protocol\":\"socks\",\"settings\":{\"auth\":\"noauth\",\"udp\":true},\"sniffing\":{\"enabled\":false}}],\"outbounds\":[{\"tag\":\"proxy\",\"protocol\":"+quote(proto)+",\"settings\":"+settings+",\"streamSettings\":"+st+"},{\"tag\":\"direct\",\"protocol\":\"freedom\"}],\"routing\":{\"domainStrategy\":\"AsIs\",\"rules\":[]}}";}
static jstring xray_policy(JNIEnv*e,jobject,jint p){if(p<1||p>65535)return nullptr;return str(e,"{\"socksListen\":\"127.0.0.1\",\"socksPort\":"+std::to_string(p)+",\"logLevel\":\"warning\",\"domainStrategy\":\"AsIs\"}");}
static jstring hyst_policy(JNIEnv*e,jobject){return str(e,"{\"startupTimeoutMs\":30000,\"recoveryTimeoutMs\":35000,\"recoveryDelayMs\":2000,\"maxRecoveryAttempts\":20,\"logDedupMs\":5000}");}
static jstring hyst_classify(JNIEnv*e,jobject,jstring line){std::string s=lower(utf(e,line));if(s.find("connected")!=std::string::npos||(s.find("socks5")!=std::string::npos&&s.find("127.0.0.1")!=std::string::npos))return str(e,"ready");if(s.find("timeout")!=std::string::npos||s.find("disconnected")!=std::string::npos||s.find("connection lost")!=std::string::npos)return str(e,"retry");if(s.find("fatal")!=std::string::npos||s.find("failed to initialize")!=std::string::npos||s.find("panic")!=std::string::npos)return str(e,"fatal");return str(e,"ignore");}
static jstring hyst_config(JNIEnv*e,jobject,jstring h,jstring p,jstring a,jstring up,jstring down,jstring obfs,jint socks){std::string host=trim(utf(e,h)),portv=trim(utf(e,p)),auth=utf(e,a),u=trim(utf(e,up)),d=trim(utf(e,down)),o=utf(e,obfs);if(host.empty()||auth.empty()||!parse_range(portv)||!parse_mbps(u)||!parse_mbps(d)||socks<1||socks>65535)return nullptr;std::string r="{\"server\":"+quote(host+":"+portv)+",\"auth_str\":"+quote(auth)+",\"up_mbps\":"+u+",\"down_mbps\":"+d+",\"retry\":3,\"retry_interval\":1,\"insecure\":true,\"recv_window_conn\":4194304,\"recv_window\":16777216,\"socks5\":{\"listen\":"+quote("127.0.0.1:"+std::to_string(socks))+"}";if(!o.empty())r+=",\"obfs\":"+quote(o);return str(e,r+"}");}
static jstring zivpn_policy(JNIEnv*e,jobject,jstring obfs){std::string o=trim(utf(e,obfs));if(o.empty())return nullptr;return str(e,"{\"argumentPrefix\":[\"-s\","+quote(o)+",\"--config\"],\"startupTimeoutMs\":5000,\"logLineMaxChars\":500}");}
static jstring zivpn_config(JNIEnv*e,jobject,jstring h,jstring p,jstring obfs,jstring a,jint socks){std::string host=trim(utf(e,h)),portv=trim(utf(e,p)),o=utf(e,obfs),auth=utf(e,a);if(host.empty()||portv.empty()||o.empty()||auth.empty()||!parse_range(portv)||socks<1||socks>65535)return nullptr;return str(e,"{\"server\":"+quote(host+":"+portv)+",\"obfs\":"+quote(o)+",\"auth\":"+quote(auth)+",\"socks5\":{\"listen\":"+quote("127.0.0.1:"+std::to_string(socks))+"},\"insecure\":true,\"recvwindowconn\":65536,\"recvwindow\":262144,\"disable_mtu_discovery\":true}");}
static jstring slow_policy(JNIEnv*e,jobject,jstring ds,jstring dp,jstring pk,jstring ns,jint dnstt,jint socks){std::string host=trim(utf(e,ds)),portv=trim(utf(e,dp)),key=trim(utf(e,pk)),resolver=trim(utf(e,ns));int parsed=0;if(host.empty()||key.empty()||resolver.empty()||!parse_port(portv,&parsed)||dnstt<1||dnstt>65535||socks<1||socks>65535)return nullptr;return str(e,"{\"argumentPrefix\":[\"-udp\","+quote(host+":"+portv)+",\"-pubkey\","+quote(key)+","+quote(resolver)+","+quote("127.0.0.1:"+std::to_string(dnstt))+"],\"dnsttReadyTimeoutMs\":8000,\"probeIntervalMs\":100,\"sshConnectTimeoutMs\":6000,\"sshKexTimeoutMs\":15000,\"sshSocksTimeoutMs\":4000,\"bannerMaxBytes\":1024,\"logLineMaxChars\":500}");}
static jstring slow_classify(JNIEnv*e,jobject,jstring line){std::string s=lower(utf(e,line));if(s.find("keepalive")!=std::string::npos)return str(e,"ignore");if(s.find("fatal")!=std::string::npos||s.find("error")!=std::string::npos||s.find("failed")!=std::string::npos||s.find("panic")!=std::string::npos)return str(e,"fatal");if(s.find("connected")!=std::string::npos||s.find("ready")!=std::string::npos)return str(e,"ready");return str(e,"info");}
static jstring xray_config(JNIEnv*e,jobject,jstring mode,jstring link,jstring raw,jint socks){std::string m=lower(trim(utf(e,mode)));if(m=="json")return str(e,utf(e,raw));std::string v=trim(utf(e,link)),vmessSource,proto,host,id,path,security,sni,streamHost,pbk,sid,fp,alpn;int port=443;if(v.rfind("vmess://",0)==0){proto="vmess";vmessSource=b64(v.substr(8));if(vmessSource.empty())return nullptr;host=trim(field(vmessSource,"add"));if(host.empty())host=trim(field(vmessSource,"host"));port=std::atoi(field(vmessSource,"port").c_str());if(port<1||port>65535)port=443;id=trim(field(vmessSource,"id"));path=decode(field(vmessSource,"path"));security=field(vmessSource,"tls");sni=trim(field(vmessSource,"sni"));if(sni.empty())sni=host;streamHost=field(vmessSource,"host");if(streamHost.empty())streamHost=sni;pbk=field(vmessSource,"pbk");sid=field(vmessSource,"sid");fp=field(vmessSource,"fp");alpn=field(vmessSource,"alpn");}else{size_t scheme=v.find("://"),start=scheme==std::string::npos?0:scheme+3;proto=lower(v.substr(0,scheme));size_t at=v.find('@',start),qpos=v.find('?',start);if(at==std::string::npos||qpos<at&&qpos!=std::string::npos)return nullptr;size_t end=qpos==std::string::npos?v.size():qpos;std::string user=decode(v.substr(start,at-start)),endpoint=v.substr(at+1,end-at-1);size_t colon=endpoint.rfind(':');host=colon==std::string::npos?endpoint:endpoint.substr(0,colon);if(colon!=std::string::npos)port=std::atoi(endpoint.substr(colon+1).c_str());id=user;std::string q=qpos==std::string::npos?"":v.substr(qpos+1);security=query(q,"security");if(security.empty())security="none";path=query(q,"path");if(path.empty())path=query(q,"serviceName");sni=query(q,"sni");if(sni.empty())sni=query(q,"servername");if(sni.empty())sni=query(q,"host");if(sni.empty())sni=host;streamHost=query(q,"host");if(streamHost.empty())streamHost=sni;pbk=query(q,"pbk");if(pbk.empty())pbk=query(q,"publicKey");sid=query(q,"sid");if(sid.empty())sid=query(q,"shortId");fp=query(q,"fp");alpn=query(q,"alpn");path=path.empty()?"/":path;std::string st=stream_cfg(query(q,"type").empty()?"tcp":query(q,"type"),security,path,streamHost,sni,pbk,sid,fp,alpn,host);std::string r=base_cfg(proto,host,port,id,"none",st,socks);std::string flow=query(q,"flow");if(!flow.empty()&&proto=="vless"){size_t p=r.find("\"users\":[{\"id\"");if(p!=std::string::npos){size_t f=r.find("}",p);r.insert(f,",\"flow\":"+quote(flow));}}return str(e,r);}if(host.empty()||id.empty())return nullptr;std::string st=stream_cfg(field(vmessSource,"net"),security,path,streamHost,sni,pbk,sid,fp,alpn,host);return str(e,base_cfg(proto,host,port,id,field(vmessSource,"scy").empty()?"auto":field(vmessSource,"scy"),st,socks));}
static jstring v2dns_policy(JNIEnv*e,jobject,jstring ds,jstring dp,jstring pk,jstring ns,jint dnstt,jint socks){std::string host=trim(utf(e,ds)),portv=trim(utf(e,dp)),key=trim(utf(e,pk)),resolver=trim(utf(e,ns));int parsed=0;if(host.empty()||key.empty()||resolver.empty()||!parse_port(portv,&parsed)||dnstt<1||dnstt>65535||socks<1||socks>65535)return nullptr;std::string args="[\"-udp\","+quote(host+":"+portv)+",\"-pubkey\","+quote(key)+","+quote(resolver)+","+quote("127.0.0.1:"+std::to_string(dnstt))+"]";std::string output="{\"argumentPrefix\":"+args+",\"dnsttReadyTimeoutMs\":10000,\"xrayReadyTimeoutMs\":9000,\"probeIntervalMs\":120,\"maxRecoveryAttempts\":15,\"recoveryDelayMs\":2000,\"logDedupMs\":5000}";return str(e,output);}
bool has_ci(const std::string&s,const std::string&needle){return lower(s).find(lower(needle))!=std::string::npos;}
std::string replace_ci(std::string s,const std::string&needle,const std::string&value){std::string lowered=lower(s),target=lower(needle);size_t p=0;while((p=lowered.find(target,p))!=std::string::npos){s.replace(p,needle.size(),value);lowered.replace(p,needle.size(),lower(value));p+=value.size();}return s;}
static jstring http_policy(JNIEnv*e,jobject,jstring sshh,jstring sshp,jstring proxyh,jstring proxyp,jstring raw){std::string host=trim(utf(e,sshh)),sport=trim(utf(e,sshp)),phost=trim(utf(e,proxyh)),pport=trim(utf(e,proxyp)),payload=utf(e,raw);int a=0,b=0;if(host.empty()||phost.empty()||!parse_port(sport,&a)||!parse_port(pport,&b))return nullptr;if(payload.empty())payload="CONNECT [host]:[port] HTTP/1.1[crlf]Host: [host]:[port][crlf]Proxy-Connection: Keep-Alive[crlf][crlf]";bool split=has_ci(payload,"[split]"),delay=has_ci(payload,"[delay]");payload=replace_ci(payload,"[host]",host);payload=replace_ci(payload,"[real_host]",host);payload=replace_ci(payload,"[port]",sport);payload=replace_ci(payload,"[proxy_host]",phost);payload=replace_ci(payload,"[proxy_port]",pport);payload=replace_ci(payload,"[crlf]","\r\n");payload=replace_ci(payload,"[cr]","\r");payload=replace_ci(payload,"[lf]","\n");payload=replace_ci(payload,"\\r\\n","\r\n");payload=replace_ci(payload,"\\r","\r");payload=replace_ci(payload,"\\n","\n");return str(e,"{\"payload\":"+quote(payload)+",\"split\":"+(split?"true":"false")+",\"delay\":"+(delay?"true":"false")+",\"connectTimeoutMs\":15000,\"responseTimeoutMs\":15000}");}
static jstring ssl_policy(JNIEnv*e,jobject,jstring sshh,jstring sshp,jstring selected,jstring sni){std::string host=trim(utf(e,sshh)),portv=trim(utf(e,sshp)),version=trim(utf(e,selected)),serverName=trim(utf(e,sni));int port=0;if(host.empty()||!parse_port(portv,&port))return nullptr;if(version.empty())version="TLS";if(version!="TLS"&&version!="TLSv1.2"&&version!="TLSv1.3")return nullptr;std::string candidates=version=="TLS"?"[\"TLS\",\"TLSv1.2\"]":"["+quote(version)+"]";return str(e,"{\"candidates\":"+candidates+",\"sni\":"+quote(serverName)+",\"connectTimeoutMs\":15000,\"handshakeTimeoutMs\":20000}");}
static jstring v2dns_classify(JNIEnv*e,jobject,jstring line){std::string s=lower(utf(e,line));if((s.find("failed to read request")!=std::string::npos&&s.find("eof")!=std::string::npos)||s.find("connection closed")!=std::string::npos)return str(e,"ignore");if(s.find("started")!=std::string::npos||s.find("ready")!=std::string::npos)return str(e,"ready");if(s.find("fatal")!=std::string::npos||s.find("panic")!=std::string::npos||s.find("failed to start")!=std::string::npos||s.find("failed to load config")!=std::string::npos)return str(e,"retry");return str(e,"ignore");}
static JNINativeMethod methods[]={{(char*)"nativeBuildXrayRuntimePolicy",(char*)"(I)Ljava/lang/String;",(void*)xray_policy},{(char*)"nativeBuildHysteriaRuntimePolicy",(char*)"()Ljava/lang/String;",(void*)hyst_policy},{(char*)"nativeClassifyHysteriaOutput",(char*)"(Ljava/lang/String;)Ljava/lang/String;",(void*)hyst_classify},{(char*)"nativeBuildHysteriaConfig",(char*)"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;",(void*)hyst_config},{(char*)"nativeBuildZiVpnRuntimePolicy",(char*)"(Ljava/lang/String;)Ljava/lang/String;",(void*)zivpn_policy},{(char*)"nativeBuildZiVpnConfig",(char*)"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;",(void*)zivpn_config},{(char*)"nativeBuildSlowDnsRuntimePolicy",(char*)"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;",(void*)slow_policy},{(char*)"nativeClassifySlowDnsOutput",(char*)"(Ljava/lang/String;)Ljava/lang/String;",(void*)slow_classify},{(char*)"nativeBuildXrayConfig",(char*)"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;",(void*)xray_config},{(char*)"nativeBuildV2RayDnsRuntimePolicy",(char*)"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;",(void*)v2dns_policy},{(char*)"nativeClassifyV2RayDnsOutput",(char*)"(Ljava/lang/String;)Ljava/lang/String;",(void*)v2dns_classify},{(char*)"nativeBuildHttpProxyPayloadRuntimePolicy",(char*)"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",(void*)http_policy},{(char*)"nativeBuildSshSslTlsRuntimePolicy",(char*)"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",(void*)ssl_policy}};
}
extern "C" JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM*vm,void*){JNIEnv*e=nullptr;if(vm->GetEnv((void**)&e,JNI_VERSION_1_6)!=JNI_OK)return JNI_ERR;jclass c=e->FindClass("expo/modules/kighmuvpnnative/OpolNative");if(!c)return JNI_ERR;jint r=e->RegisterNatives(c,methods,sizeof(methods)/sizeof(methods[0]));e->DeleteLocalRef(c);return r==JNI_OK?JNI_VERSION_1_6:JNI_ERR;}
